project:
  type: website
  output-dir: docs

website:
  title: "mcewenkhundi"
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/mcewenkhundi
      - icon: twitter
        href: https://twitter.com/MacKhundi
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

