project:
  type: website
  output-dir: docs

website:
  title: "McEwen Khundi"
  repo-url: https://github.com/mcewenkhundi/mcewenkhundi
  favicon: dice-4.png
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/mcewenkhundi
      - icon: twitter
        href: https://twitter.com/MacKhundi
  page-footer: 
    left:
      - text: "Copyright 2022, McEwen Khundi." 
        href: about.qmd
      - text: "Made with Quarto"
        href: https://quarto.org/

    right: 
      - text: Blog Source
        href: https://github.com/mcewenkhundi/mcewenkhundi 
    
format:
  html:
    theme:
     light: flatly
     dark: darkly
    css: styles.css

editor: visual


