project:
  type: website
  output-dir: docs

website:
  title: "McEwen Khundi Blog"
  repo-url: https://github.com/mcewenkhundi/mcewenkhundi
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/mcewenkhundi
      - icon: twitter
        href: https://twitter.com/MacKhundi
  page-footer: 
    left: "Copyright 2022, McEwen Khundi. Made with Quarto."
    
    right: 
      - icon: github
        href: https://github.com/mcewenkhundi
      - icon: twitter 
        href: https://twitter.com/MacKhundi  
    
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

